blogTitle = "Yuppies"
mastHead = "YUPPI.ES"
authorName = "Siddharth Jain"
shortName = "f0rr0"
linkPrefix = ""
description = "By Siddharth Jain — an open source developer interested in minimal design, advanced JavaScript and everything λ. He is currently available for contract development on a project basis."
